### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by hatyi** [hoffmanng/ingatlan-com-scraper#25]
Hello!

This project looks awesome and would be very useful for me currently, but I'm getting HTTP 403 with the URLs provided in the readme file.
Seems like the same error as what the 1.1.0 version fixed (at least I'm guessing this based on the HTTP status code).

Is there any chance for you to review or maintain the project?

This is what I see in my terminal:
>hatyi@localhost:~/docker-stuff/ingatlancom/src/ingatlan-com-scraper$ npm start https://ingatlan.com/lista/elado+lakas+ix-ker+25-m2-alatt https://ingatlan.com/lista/elado+lakas+debrecen+25-m2-alatt

> ingatlan-com-scraper@1.0.0 start /home/hatyi/docker-stuff/ingatlancom/src/ingatlan-com-scraper
> npm run cron "https://ingatlan.com/lista/elado+lakas+ix-ker+25-m2-alatt" "https://ingatlan.com/lista/elado+lakas+debrecen+25-m2-alatt"

> ingatlan-com-scraper@1.0.0 cron /home/hatyi/docker-stuff/ingatlancom/src/ingatlan-com-scraper
> node src/cron.js "https://ingatlan.com/lista/elado+lakas+ix-ker+25-m2-alatt" "https://ingatlan.com/lista/elado+lakas+debrecen+25-m2-alatt"

>Request failed with status code 403
>Request failed with status code 403

I've tried the Docker version first (because of the ease of use) it creates the data folder but after running for 12h it was empty, so I'm guessing the same thing is happening there.

Best regards
Hatyi

**Comment by hoffmanng** [comment]
Sorry, they have added cloudflare's bot protection. I will not update this repository to get around that.
